name: Deploy Dev

on:
  workflow_dispatch:
    inputs:
      version:
        default: dev

env:
  REGISTRY: crpi-4gjhfmn9d3r2c9et.cn-hangzhou.personal.cr.aliyuncs.com
  NAMESPACE: financial-admin
  IMAGE_NAME: financial-admin

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set tag
        run: echo "IMAGE_TAG=${{ github.event.inputs.version }}" >> $GITHUB_ENV

      - name: Login ACR
        run: |
          echo "${{ secrets.ACR_PASSWORD }}" | docker login $REGISTRY \
          --username ${{ secrets.ACR_USERNAME }} \
          --password-stdin

      - name: Build image
        run: |
          docker build -t $REGISTRY/$NAMESPACE/$IMAGE_NAME:$IMAGE_TAG .

      - name: Push image
        run: |
          docker push $REGISTRY/$NAMESPACE/$IMAGE_NAME:$IMAGE_TAG

      - name: Checkout k3s-configs
        uses: actions/checkout@v4
        with:
          repository: sujdfjio112/k3s-configs
          token: ${{ secrets.GH_TOKEN }}
          path: k3s-configs

      - name: Update image
        run: |
          IMAGE="$REGISTRY/$NAMESPACE/$IMAGE_NAME:$IMAGE_TAG"
          sed -i "s|image: .*|image: $IMAGE|" k3s-configs/apps/financial-admin/deployment.yaml

      - name: Commit and push
        run: |
          cd k3s-configs
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "deploy financial-admin:$IMAGE_TAG"
          git push